services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    

    

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092  
      KAFKA_CFG_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  producer:
    build: ./Producer
    depends_on:
      - kafka

  notificationservice:
    build: ./Consumer
    depends_on:
      - kafka

  analyticsservice:
    build: ./AnalyticsService
    depends_on:
      - kafka